language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
install:
  - pip install -r requirements.txt
  - python generate_nightly_config.py
script:
  - bash -c "python test.py configs/config_*_nightly.ini"

